### PR TITLE
Fix index.html

### PR DESCRIPTION
**Pull request by technoboy10**
My bad - I missed a tweak that I made to index.html in the main repository that breaks this one! This should fix it.

### CODE REVIEW

**Comment by LiFaytheGoblin** [comment]
Doesn't work for me :(

**Comment by technoboy10** [comment]
Lemme take a look.

**Comment by technoboy10** [comment]
Looks like it was a problem with crossorigin.me and a lot of lag. It should work now (although it tends to get really laggy every day :/)

**Comment by LiFaytheGoblin** [comment]
For some reason, for me it doesn't load the number of projects on the waitiung list and when clicking next project it redirects to the Scratch main page... So sorry for all the inconvenience :(

**Comment by LiFaytheGoblin** [comment]
I did some testing and it doesn't seem to do anything after 

`axios.all([getID(), getPeople('owners', getID), getPeople('curators', getID)])`

No idea what that means o.O

**Comment by technoboy10** [comment]
Yeah, I seem to get lag spikes when the amount of requests to the server is high. Working on fixing that. :/

**Comment by LiFaytheGoblin** [comment]
Thank you so much @technoboy10

**Pull request merged**
